# Generated by Django 3.2.4 on 2021-06-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
