# Generated by Django 3.2.4 on 2021-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_delete_user_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
