# Generated by Django 3.2.4 on 2021-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alert', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAlert',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alertname', models.CharField(max_length=100, verbose_name='告警名称')),
                ('alerttype', models.CharField(max_length=100, verbose_name='告警类型')),
            ],
        ),
    ]
