# Generated by Django 3.2.4 on 2021-07-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_auto_20210706_1049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historyalert',
            table='history_alert',
        ),
    ]
