# Generated by Django 3.2.4 on 2021-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210721_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlReplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=40, verbose_name='business')),
                ('rp', models.CharField(blank=True, max_length=10, verbose_name='rp')),
                ('master_ip', models.CharField(max_length=40, verbose_name='master_ip')),
                ('slave_ip', models.CharField(max_length=40, verbose_name='slave_ip')),
                ('rp_status', models.CharField(blank=True, max_length=40, verbose_name='rp_status')),
            ],
            options={
                'db_table': 'mysql_replication',
                'ordering': ['projectname'],
            },
        ),
    ]
