# Generated by Django 3.2.4 on 2021-08-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210813_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(blank=True, max_length=40, verbose_name='business')),
                ('createtime', models.CharField(blank=True, max_length=50, verbose_name='创建时间')),
                ('modifytime', models.CharField(blank=True, max_length=50, verbose_name='修改时间')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='状态')),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='projectname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmdb_product', to='common.product', verbose_name='所属产品'),
        ),
    ]
