# Generated by Django 3.2.4 on 2021-08-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210813_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status']},
        ),
    ]
