# Generated by Django 3.2.4 on 2021-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='projectname',
            field=models.CharField(blank=True, max_length=40, verbose_name='所属产品'),
        ),
    ]
