# Generated by Django 3.2.4 on 2021-08-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='projectname',
            field=models.CharField(blank=True, max_length=40, verbose_name='产品'),
        ),
    ]
