# Generated by Django 3.2.4 on 2021-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210816_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务注册ID')),
                ('record_time', models.CharField(blank=True, max_length=80, verbose_name='注销时间')),
            ],
            options={
                'db_table': 'CancellationRecord',
                'ordering': ['record_time'],
            },
        ),
    ]
