# Generated by Django 3.2.4 on 2021-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_mysqlreplication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayCmdb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cmdb_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务ID')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名')),
                ('serverip', models.CharField(blank=True, max_length=20, null=True, verbose_name='地址')),
                ('cpuinfo', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPU')),
                ('diskinfo', models.CharField(blank=True, max_length=20, null=True, verbose_name='磁盘')),
                ('meminfo', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存')),
                ('projectname', models.CharField(blank=True, max_length=40, null=True, verbose_name='产品')),
                ('ostype', models.CharField(blank=True, max_length=40, null=True, verbose_name='机器类型')),
                ('datacenter', models.CharField(blank=True, max_length=20, null=True, verbose_name='归属机房')),
                ('projectenv', models.CharField(blank=True, max_length=20, null=True, verbose_name='服务环境')),
                ('projectadmin', models.CharField(blank=True, max_length=20, null=True, verbose_name='产品管理员')),
                ('createtime', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建时间')),
                ('modifytime', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改时间')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='虚机状态')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'TodayCmdb',
                'ordering': ['-createtime'],
            },
        ),
        migrations.AlterModelOptions(
            name='mysqlreplication',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='record_time',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='注销时间'),
        ),
        migrations.AlterField(
            model_name='mysqlreplication',
            name='master_ip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='master_ip'),
        ),
        migrations.AlterField(
            model_name='mysqlreplication',
            name='projectname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='mysqlreplication',
            name='rp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='rp'),
        ),
        migrations.AlterField(
            model_name='mysqlreplication',
            name='rp_status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='rp_status'),
        ),
        migrations.AlterField(
            model_name='mysqlreplication',
            name='slave_ip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='slave_ip'),
        ),
    ]
