# Generated by Django 3.2.4 on 2021-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_elknginxstatus404'),
    ]

    operations = [
        migrations.AddField(
            model_name='elknginxstatus404',
            name='search_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='search_time'),
        ),
    ]
