# Generated by Django 3.2.4 on 2021-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_rename_status_404_elknginxstatus500_status_500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elknginxstatus404',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elknginxstatus500',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
