# Generated by Django 3.2.4 on 2021-12-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20211011_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomonitorcmdb',
            options={'ordering': ['-createtime']},
        ),
    ]
