# Generated by Django 3.2.4 on 2021-07-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_todaycmdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodayCmdb',
            new_name='NoMonitorCmdb',
        ),
        migrations.AlterModelTable(
            name='nomonitorcmdb',
            table='NoMonitorCmdb',
        ),
    ]
