# Generated by Django 3.2.4 on 2021-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomonitorcmdb',
            name='projectname',
            field=models.CharField(blank=True, max_length=40, verbose_name='所属产品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='projectname',
            field=models.CharField(blank=True, max_length=40, verbose_name='所属产品'),
        ),
    ]
