# Generated by Django 3.2.4 on 2021-08-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_remove_cmdb_projectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
