# Generated by Django 3.2.4 on 2021-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_cancellationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='service_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='服务注册ID'),
        ),
    ]
