# Generated by Django 3.2.4 on 2021-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_cancellationrecord_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlreplication',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
