# Generated by Django 3.2.4 on 2021-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20211011_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='elknginxstatus404',
            name='search_time_stamp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='search_time'),
        ),
        migrations.AddField(
            model_name='elknginxstatus500',
            name='search_time_stamp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='search_time'),
        ),
    ]
