# Generated by Django 3.2.4 on 2021-07-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
