# Generated by Django 3.2.4 on 2021-07-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_auto_20210706_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyalert',
            options={'ordering': ['-sendtime']},
        ),
        migrations.AlterModelTable(
            name='historyalert',
            table='HistoryAlert',
        ),
    ]
