# Generated by Django 3.2.4 on 2021-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_alter_historyalert_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertname', models.CharField(max_length=100, verbose_name='告警名称')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='状态')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='告警级别')),
                ('env', models.CharField(blank=True, max_length=20, verbose_name='环境')),
                ('idc', models.CharField(blank=True, max_length=20, verbose_name='机房')),
                ('business', models.CharField(blank=True, max_length=20, verbose_name='业务')),
                ('instance', models.CharField(blank=True, max_length=50, verbose_name='实例')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP')),
                ('port', models.CharField(blank=True, max_length=50, verbose_name='PORT')),
                ('summary', models.CharField(blank=True, max_length=1000, verbose_name='告警主旨')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='告警信息')),
                ('startsAt', models.CharField(blank=True, max_length=80, verbose_name='告警产生时间')),
                ('endsAt', models.CharField(blank=True, max_length=80, verbose_name='告警恢复时间')),
                ('sendtime', models.CharField(blank=True, max_length=80, verbose_name='告警发送时间')),
                ('caltime', models.CharField(blank=True, max_length=80, verbose_name='异常时间')),
                ('fingerprint', models.CharField(blank=True, max_length=80, verbose_name='fingerprint')),
            ],
            options={
                'db_table': 'time_alert',
                'ordering': ['-sendtime'],
            },
        ),
    ]
